config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'my_page_edit'
    patch 'customers/information' => 'customers#update', as: 'my_page_update'
    patch 'customers/withdraw'
    get 'customers/confirm'
    delete 'cart_items/destroy_all'
    post 'orders/confirm'
    get 'orders/complete'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    if params[:search]
      @items = Item.where("name LIKE ? ", '%' + params[:search] + '%')
      @items = @items.page(params[:page]).per(10)
    else
      @items = Item.page(params[:page]).per(10)
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <h2>商品編集</h2>
  </div>
  <div class="row mt-3">
    <div class="col-lg-8">
    <%= form_with model: @item, url: admin_item_path do |f| %>
      <table class="table table-borderless">
        <tr>
          <td><label for="item_image">商品画像</label></td>
          <td><%= f.file_field :image, id:"item_image", accept: "image/*" %></td>
        </tr>
        <tr>
          <td><label for="item_name">商品名</label></td>
          <td><%= f.text_field :name, id:"item_name" %></td>
        </tr>
        <tr>
          <td><label for="item_introduction">商品説明</label></td>
          <td><%= f.text_area :introduction, id:"item_introduction" %></td>
        </tr>
        <tr>
          <td><label>ジャンル</label></td>
          <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
        </tr>
        <tr>
          <td><label for "item_price">税抜価格</label></td>
          <td><%= f.text_field :price, id:"item_price" %></td>
        </tr>
        <tr>
          <td><label>販売ステータス</label></td>
          <td>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active_true, "販売中" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active_false, "販売停止中" %>
          </td>
        </tr>
      </table>
      <div class="row mt-3">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
    <div class="col-lg-4"></div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-11">
      <h2>商品一覧</h2>
    </div>
    <div class="col-lg-1">
      <%= link_to new_admin_item_path do %>
        <i class="fa-solid fa-circle-plus fa-3x" style="color: gainsboro;"></i>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th>商品ID</th><th>商品名</th><th>税抜価格</th><th>ジャンル</th><th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id), class: "text-dark" do %>
                <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
          <% if item.is_active %>
            <td class="text-success">販売中</td>
          <% else %>
            <td class="text-secondary">販売停止中</td>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row mt-3">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
      <%= paginate @items %>
    </div>
    <div class="col-lg-4"></div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row mt-3">
    <h2>商品新規登録</h2>
  </div>
  <% if @item.errors.any? %>
  <div class="row mt-3">
    <h5><%= @item.errors.count %>件のエラーが発生しました</h5>
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row mt-3">
    <div class="col-lg-10">
      <%= form_with model: @item, url: admin_items_path do |f| %>
        <table class="table table-borderless">
          <tr>
            <td><label for="inputImage"><strong>商品画像</strong></label></td>
            <td><%= f.file_field :image, id:"inputImage", accept: "image/*" %></td>
          </tr>
          <tr>
            <td><label for="inputItemName"><strong>商品名</strong></label></td>
            <td><%= f.text_field :name, id:"inputItemName" %></td>
          </tr>
          <tr>
            <td><label for="inputIntroduction"><strong>商品説明</strong></label></td>
            <td><%= f.text_area :introduction, id:"inputIntroduction" %></td>
          </tr>
          <tr>
            <td><label><strong>ジャンル</strong></label></td>
            <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
          </tr>
          <tr>
            <td><label for "inputPrice"><strong>税抜価格</strong></label></td>
            <td><%= f.text_field :price, id:"inputPrice" %></td>
          </tr>
          <tr>
            <td><label><strong>販売ステータス</strong></label></td>
            <td>
              <%= f.radio_button :is_active, true %>
              <strong><%= f.label :is_active_true, "販売中" %></strong>
              <%= f.radio_button :is_active, false %>
              <strong><%= f.label :is_active_false, "販売停止中" %></strong>
            </td>
          </tr>
        </table>
        <div class="row col-sm-3 mt-3 mx-auto">
          <%= f.submit "新規登録", class: "btn btn-lg btn-success" %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mt-5">
    <h2>商品詳細</h2>
  </div>
  <div class="row mt-3">
    <div class="col-lg-4 mt-5">
      <%= image_tag @item.get_image(300,200) %>
    </div>
    <div class="col-lg-8 mt-5">
      <table class="table table-borderless">
        <tr>
          <td scope="col" style="width: 30%"><strong>商品名</strong></td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td scope="col" style="width: 30%"><strong>商品説明</strong></td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td scope="col" style="width: 30%"><strong>ジャンル</strong></td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td scope="col" style="width: 30%"><strong>税込価格(税抜価格)</strong></td>
          <td>¥<%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)</td>
        </tr>
        <tr>
          <td scope="col" style="width: 30%"><strong>販売ステータス</strong></td>
          <% if @item.is_active %>
            <td class="text-success"><strong>販売中</strong></td>
          <% else %>
            <td class="text-secondary"><strong>販売停止中</strong></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="row mt-3 text-center">
    <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
  </div>
</div>