config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'my_page_edit'
    patch 'customers/information' => 'customers#update', as: 'my_page_update'
    patch 'customers/withdraw'
    get 'customers/confirm'
    delete 'cart_items/destroy_all'
    post 'orders/confirm'
    get 'orders/complete'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
  </div>
  <div class="row mt-3">
    <%= form_with model: @customer, url: admin_customer_path do |f| %>
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td><%= f.label :氏名 %></td>
          <td><%= f.text_field :last_name %></td><td><%= f.text_field :first_name %></td>
        </tr>
        <tr>
          <td><%= f.label :フリガナ %></td>
          <td><%= f.text_field :last_name_kana %></td><td><%= f.text_field :first_name_kana %></td>
        </tr>
        <tr>
          <td><%= f.label :郵便番号 %></td>
          <td><%= f.text_field :postal_code %></td>
        </tr>
        <tr>
          <td><%= f.label :住所 %></td>
          <td><%= f.text_field :address %></td>
        </tr>
        <tr>
          <td><%= f.label :電話番号 %></td>
          <td><%= f.text_field :telephone_number %></td>
        </tr>
        <tr>
          <td><%= f.label :メールアドレス %></td>
          <td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <td><%= f.label :会員ステータス %></td>
          <td>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted_false, "有効" %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted_true, "退会" %>
          </td>
        </tr>
      </table>
      <div class="col-lg-3 ml-5">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mt-3">
    <h2>会員一覧</h2>
  </div>
  <div class="row mt-3">
    <table class="table table-hover">
      <thead class="table-active">
        <th>会員ID</th><th>氏名</th><th>メールアドレス</th><th>ステータス</th>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id), class: "text-dark" do %>
              <%= customer.last_name %><%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <% if customer.is_deleted %>
            <td class="text-secondary">退会</td>
          <% else %>
            <td class="text-success">有効</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
      <%= paginate @customers %>
    </div>
    <div class="col-lg-4"></div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-5">
    <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
  </div>
  <table class="table table-borderless">
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <% if @customer.is_deleted %>
        <td class="text-secondary">退会</td>
      <% else %>
        <td class="text-success">有効</td>
      <% end %>
    </tr>
  </table>
  <div class="row mt-5">
    <div class="col-lg-3">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
    </div>
    <div class="col-lg-1"></div>
    <div class="col-lg-3">
      <%= link_to "注文履歴一覧を見る", admin_root_path(customer_id: @customer), class: "btn btn-primary" %>
    </div>
    <div class="col-lg-5"></div>
  </div>
</div>