config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'my_page_edit'
    patch 'customers/information' => 'customers#update', as: 'my_page_update'
    patch 'customers/withdraw'
    get 'customers/confirm'
    delete 'cart_items/destroy_all'
    post 'orders/confirm'
    get 'orders/complete'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page]).per(5)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.page(params[:page]).per(5)
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <h2>ジャンル編集</h2>
  </div>
  <div class="row mt-3">
    <%= form_with model: @genre, url: admin_genre_path do |f| %>
      <label for="genre_name">ジャンル名</label>
      <%= f.text_field :name, id:"genre_name" %>
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row mt-5">
    <h2>ジャンル一覧・追加</h2>
  </div>
  <% if @genre.errors.any? %>
  <div class="row mt-3">
    <h5><%= @genre.errors.count %>件のエラーが発生しました</h5>
    <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row mt-3">
    <div class="col-lg-6">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <label for="inputGenreName">ジャンル名</label>
        <%= f.text_field :name, autofocus: true, id:"inputGenreName", placeholder:"ジャンル名"%>
        <%= f.submit "新規登録", class: "btn btn-success" %>
      <% end %>
    </div>
    <div class="col-lg-6"></div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-8 float-left">
      <table class="table table-hover">
        <thead class="table-active">
          <th>ジャンル</th><th></th>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
      <%= paginate @genres %>
    </div>
    <div class="col-lg-4"></div>
  </div>
</div>